<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <LangVersion>14</LangVersion>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="OsborneSupremacy.Extensions.AspNet" Version="8.0.0" />
    <PackageReference Include="Spectre.Console" Version="0.50.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Broadcast.Prep.Data\Broadcast.Prep.Data.csproj" />
    <ProjectReference Include="..\BroadCast.Prep.Models\BroadCast.Prep.Models.csproj" />
  </ItemGroup>

</Project>
